# Generated by Django 3.2 on 2022-10-05 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='chat.message'),
        ),
    ]
