# Generated by Django 3.2 on 2022-10-05 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.statusmessage'),
        ),
    ]
